In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

1. Create a null vector of size 10 but the fifth value which is 1.

In [3]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.

In [4]:
Z=np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [6]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


5. Create a 10x10 array with random values and find the minimum and maximum values.

In [7]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0011526662478981153 0.9966507918352165


6. Create a random vector of size 30 and find the mean value.

In [8]:
Z = np.random.random(10)
m = Z.mean()
print(m)

0.5694620752673973
